# Express 예외 처리

 - `예외 발생시키기`
    - throw 키워드로 에러를 발생시킬 수 있다.
    - 만약, 에러 처리기 없는 경우 에러가 발생하면 서버가 종료된다.(Crash)
```javascript
app.get('/', (req, res) => {
    throw new Error('This is Error');
});
```

<br/>

 - `예외 핸들링`
    - Express는 에러가 발생하면 에러 처리기로 보내준다.
    - 인자가 4개인 미들웨어 함수는 에러 처리기로 동작한다.
```javascript
app.use((error, req, res, next) => {
    res.json({ message: error.message });
});
```

<br/>

 - `비동기 예외`
    - 비동기 요청으로 인한 에러는 에러 처리기가 받지 못한다. 때문에, throw 키워드가 아닌 next() 메서드를 이용한다.
```javascript
// ❌ 
app.get('/', (req, res) => {
    setImmediate(() => {
        throw new Error('This is Error');
    });
});

// ✔
app.get('/', (req, res, next) => {
    setImmediate(() => {
        next(new Error('This is Error'));
    });
});

// ✔: 비동기 요청에 대해서 try catch로 묶고, 에러를 next()로 전달한다.
app.get('/', (req, res, next) => {
    try {
        setImmediate(() => {
            throw new Error('This is Error');
        });
    } catch (error) {
        next(error);
    }
});
```
