# Exception Filters

 - 공식 문서: https://docs.nestjs.com/exception-filters

NestJS에서 Exception Filters는 애플리케이션에서 발생하는 예외를 처리하는 데 사용되는 메커니즘입니다. Exception Filter는 발생한 예외를 캐치하여 응답을 제어하거나, 로깅하는 등의 작업을 수행할 수 있게 해줍니다. NestJS는 기본적으로 HTTP 예외를 처리하는 빌트인 필터를 제공하지만, 커스텀 필터를 정의하여 더 복잡한 예외 처리 로직을 구현할 수 있습니다.  

## NestJS 내장 Exception

NestJS는 다양한 내장 예외 클래스를 제공하여 애플리케이션에서 발생하는 다양한 상황에 대해 적절한 예외를 던질 수 있도록 합니다. 이러한 예외 클래스는 HttpException을 상속하며, HTTP 상태 코드를 기반으로 예외를 정의합니다.  

 - HttpException
    - 기본 예외 클래스입니다. 모든 커스텀 예외 클래스는 이 클래스를 상속받아 생성할 수 있습니다.
    - 생성자: new HttpException(response: string | object, status: number)
 - BadRequestException (400)
    - 클라이언트의 요청이 잘못되었을 때 사용됩니다.
    - 생성자: new BadRequestException(message?: string | object)
 - UnauthorizedException (401)
    - 인증이 필요하지만 제공되지 않았거나 실패했을 때 사용됩니다.
    - 생성자: new UnauthorizedException(message?: string | object)
 - NotFoundException (404)
    - 요청한 리소스를 찾을 수 없을 때 사용됩니다.
    - 생성자: new NotFoundException(message?: string | object)
 - ForbiddenException (403)
    - 클라이언트가 요청한 리소스에 접근할 권한이 없을 때 사용됩니다.
    - 생성자: new ForbiddenException(message?: string | object)
 - MethodNotAllowedException (405)
    - 요청한 HTTP 메서드가 허용되지 않을 때 사용됩니다.
    - 생성자: new MethodNotAllowedException(message?: string | object)
 - NotAcceptableException (406)
    - 클라이언트가 요청한 미디어 타입을 서버가 제공할 수 없을 때 사용됩니다.
    - 생성자: new NotAcceptableException(message?: string | object)
 - RequestTimeoutException (408)
    - 서버가 클라이언트의 요청을 시간 내에 처리하지 못했을 때 사용됩니다.
    - 생성자: new RequestTimeoutException(message?: string | object)
 - ConflictException (409)
    - 리소스의 현재 상태와 충돌하는 요청이 들어왔을 때 사용됩니다.
    - 생성자: new ConflictException(message?: string | object)
 - GoneException (410)
    - 요청한 리소스가 더 이상 사용할 수 없을 때 사용됩니다.
    - 생성자: new GoneException(message?: string | object)
 - PayloadTooLargeException (413)
    - 요청한 페이로드가 너무 클 때 사용됩니다.
    - 생성자: new PayloadTooLargeException(message?: string | object)
 - UnsupportedMediaTypeException (415)
    - 서버가 지원하지 않는 미디어 타입을 클라이언트가 요청했을 때 사용됩니다.
    - 생성자: new UnsupportedMediaTypeException(message?: string | object)
 - UnprocessableEntityException (422)
    - 서버가 요청을 이해했지만, 처리할 수 없을 때 사용됩니다. 주로 데이터 유효성 검사 실패 시 사용됩니다.
    - 생성자: new UnprocessableEntityException(message?: string | object)
 - InternalServerErrorException (500)
    - 서버 내부에서 예기치 않은 오류가 발생했을 때 사용됩니다.
    - 생성자: new InternalServerErrorException(message?: string | object)
 - NotImplementedException (501)
    - 서버가 요청된 기능을 지원하지 않을 때 사용됩니다.
    - 생성자: new NotImplementedException(message?: string | object)
 - BadGatewayException (502)
    - 서버가 게이트웨이 또는 프록시로서 잘못된 응답을 받았을 때 사용됩니다.
    - 생성자: new BadGatewayException(message?: string | object)
 - ServiceUnavailableException (503)
    - 서버가 현재 요청을 처리할 수 없을 때 사용됩니다. 주로 서버가 과부하 상태이거나 유지 보수 중일 때 사용됩니다.
    - 생성자: new ServiceUnavailableException(message?: string | object)
 - GatewayTimeoutException (504)
    - 서버가 게이트웨이 또는 프록시로서 요청을 처리하는 동안 시간 초과가 발생했을 때 사용됩니다.
    - 생성자: new GatewayTimeoutException(message?: string | object)

<br/>

### 표준 예외 발생시키기

```typescript
@Get()
async findAll() {
  throw new HttpException('Forbidden', HttpStatus.FORBIDDEN);
}

@Get(':id')
async findById(@Param('id') id: string) {
  try {
    const item = await this.service.findById(id);
    if (!item) {
      throw new NotFoundException(`Item with id ${id} not found`);
    }
  } catch (error) {
    throw new HttpException({
      status: HttpStatus.FORBIDDEN,
      error: 'This is a custom message',
    }, HttpStatus.FORBIDDEN, {
      cause: error
    });
  }

  return item;
}
```
<br/>

## Exception Filter

 - `http-exception.filter.ts`
```typescript
import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';
import { Request, Response } from 'express';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = exception.getStatus();

    response
      .status(status)
      .json({
        statusCode: status,
        timestamp: new Date().toISOString(),
        path: request.url,
      });
  }
}
```

 - `main.ts`
    - 커스텀하게 만든 ExceptionFilter를 전역으로 등록한다.
```typescript
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalFilters(new HttpExceptionFilter());
  await app.listen(3000);
}
bootstrap();
```
<br/>

### 특정 컨트롤러에만 필터 적용

```typescript
import { Controller, Get, UseFilters } from '@nestjs/common';

@Controller('cats')
@UseFilters(new HttpExceptionFilter())
export class CatsController {
  @Get()
  findAll() {
    throw new HttpException('Forbidden', 403);
  }
}
```
